[config]
skip_core_tasks = true
default_to_workspace = false


[tasks.default]
dependencies = ["start"]

[tasks.start]
description = "Start server"
command = "cargo"
args = ["run"]
dependencies = ["client", "server"]

[tasks.server]
description = "Build server"
command = "cargo"
args = ["build", "--bin", "server"]

[tasks.client]
description = "Build client"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]

[tasks.client]
description = "Make Client"
command = "cargo"
args = ["make", "--cwd", "client"]
