[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
dependencies = ["start"]

[tasks.start]
description = "Start Server"
command = "cargo"
args = ["run", "${@}"]

[tasks.check]
description = "Check Server"
command = "cargo"
args = ["check", "--bin", "server"]

[tasks.build]
description = "Build server"
command = "cargo"
args = ["build", "${@}"]

[tasks.clean]
description = "Clean Server"
command = "cargo"
args = ["clean"]
