#![feature(async_closure)]
extern crate chrono;
extern crate serde;
extern crate serde_json;
extern crate http;
extern crate anyhow;
extern crate futures;
extern crate wasm_bindgen_futures;
extern crate url;
extern crate wasm_bindgen;
extern crate rql;
extern crate plans;
extern crate budget;
extern crate updatable;
extern crate database;
extern crate seed;
#[macro_use] extern crate lazy_static;

pub mod login;
pub mod register;
pub mod home;
pub mod navbar;
pub mod users;
pub mod page;
pub mod root;
pub use root::*;
pub mod fetched;
pub mod route;
pub mod storage;
pub mod request;
